/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.mz.bennypecas.visao;

import co.mz.bennypecas.controladores.Registo;
import co.mz.bennypecas.modelos.Alerta;
import co.mz.bennypecas.modelos.Produto;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Euclidio G. Venâncio
 */
public class Usuario extends javax.swing.JFrame {

    public Usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelRegistoProdutos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCombCategoria = new javax.swing.JComboBox<>();
        nomeProduto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        modeloProduto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tipoProduto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        numeroProduto = new javax.swing.JTextField();
        estadoProduto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricaoProduto = new javax.swing.JEditorPane();
        jLabel22 = new javax.swing.JLabel();
        caracteristicaProduto = new javax.swing.JTextField();
        PainelRegistoProdutos1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCombCategoria1 = new javax.swing.JComboBox<>();
        nomeProduto1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        modeloProduto1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tipoProduto1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        numeroProduto1 = new javax.swing.JTextField();
        estadoProduto1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descricaoProduto1 = new javax.swing.JEditorPane();
        jLabel30 = new javax.swing.JLabel();
        caracteristicaProduto1 = new javax.swing.JTextField();
        PainelRegistoUsuario = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jL_nome = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLpreco = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPainelDescricao = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jCestado = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLmodelo = new javax.swing.JTextField();
        jBtn_Save = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListModeloRef = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSquant = new javax.swing.JSpinner();

        PainelRegistoProdutos.setBackground(new java.awt.Color(244, 255, 255));
        PainelRegistoProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel3.setText("Categoria");
        PainelRegistoProdutos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel15.setText("Nome ");
        PainelRegistoProdutos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jCombCategoria.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jCombCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha . . .", "Acessórios", "Peças" }));
        jCombCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombCategoriaItemStateChanged(evt);
            }
        });
        PainelRegistoProdutos.add(jCombCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, 30));

        nomeProduto.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        nomeProduto.setToolTipText("Necessário");
        nomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoActionPerformed(evt);
            }
        });
        PainelRegistoProdutos.add(nomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, 30));

        jLabel16.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel16.setText("Modelo");
        PainelRegistoProdutos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        modeloProduto.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        modeloProduto.setToolTipText("Necessário");
        modeloProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloProdutoActionPerformed(evt);
            }
        });
        PainelRegistoProdutos.add(modeloProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, 30));

        jLabel17.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel17.setText("Tipo ");
        PainelRegistoProdutos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        tipoProduto.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        tipoProduto.setToolTipText("Necessário");
        tipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoProdutoActionPerformed(evt);
            }
        });
        PainelRegistoProdutos.add(tipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 230, 30));

        jLabel18.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel18.setText("Número");
        PainelRegistoProdutos.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        numeroProduto.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        numeroProduto.setToolTipText("Necessário");
        numeroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroProdutoActionPerformed(evt);
            }
        });
        PainelRegistoProdutos.add(numeroProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 240, 30));

        estadoProduto.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        estadoProduto.setToolTipText("Necessário");
        estadoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoProdutoActionPerformed(evt);
            }
        });
        PainelRegistoProdutos.add(estadoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 240, 30));

        jLabel19.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel19.setText("Estado ");
        PainelRegistoProdutos.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 204));
        jLabel20.setText("____________________________________________________________________________________________________________________________________________");
        PainelRegistoProdutos.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel21.setText("Descrição");
        PainelRegistoProdutos.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jScrollPane2.setViewportView(descricaoProduto);

        PainelRegistoProdutos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 230, 160));

        jLabel22.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel22.setText("Características");
        PainelRegistoProdutos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        caracteristicaProduto.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        caracteristicaProduto.setToolTipText("Necessário");
        caracteristicaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caracteristicaProdutoActionPerformed(evt);
            }
        });
        PainelRegistoProdutos.add(caracteristicaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 240, 30));

        PainelRegistoProdutos1.setBackground(new java.awt.Color(244, 255, 255));
        PainelRegistoProdutos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel4.setText("Categoria");
        PainelRegistoProdutos1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel23.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel23.setText("Nome ");
        PainelRegistoProdutos1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jCombCategoria1.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jCombCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha . . .", "Acessórios", "Peças" }));
        jCombCategoria1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombCategoria1ItemStateChanged(evt);
            }
        });
        PainelRegistoProdutos1.add(jCombCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, 30));

        nomeProduto1.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        nomeProduto1.setToolTipText("Necessário");
        nomeProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProduto1ActionPerformed(evt);
            }
        });
        PainelRegistoProdutos1.add(nomeProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, 30));

        jLabel24.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel24.setText("Modelo");
        PainelRegistoProdutos1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        modeloProduto1.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        modeloProduto1.setToolTipText("Necessário");
        modeloProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloProduto1ActionPerformed(evt);
            }
        });
        PainelRegistoProdutos1.add(modeloProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, 30));

        jLabel25.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel25.setText("Tipo ");
        PainelRegistoProdutos1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        tipoProduto1.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        tipoProduto1.setToolTipText("Necessário");
        tipoProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoProduto1ActionPerformed(evt);
            }
        });
        PainelRegistoProdutos1.add(tipoProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 230, 30));

        jLabel26.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel26.setText("Número");
        PainelRegistoProdutos1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        numeroProduto1.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        numeroProduto1.setToolTipText("Necessário");
        numeroProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroProduto1ActionPerformed(evt);
            }
        });
        PainelRegistoProdutos1.add(numeroProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 240, 30));

        estadoProduto1.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        estadoProduto1.setToolTipText("Necessário");
        estadoProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoProduto1ActionPerformed(evt);
            }
        });
        PainelRegistoProdutos1.add(estadoProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 240, 30));

        jLabel27.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel27.setText("Estado ");
        PainelRegistoProdutos1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 204, 204));
        jLabel28.setText("____________________________________________________________________________________________________________________________________________");
        PainelRegistoProdutos1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jLabel29.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel29.setText("Descrição");
        PainelRegistoProdutos1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jScrollPane3.setViewportView(descricaoProduto1);

        PainelRegistoProdutos1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 230, 160));

        jLabel30.setFont(new java.awt.Font("Rubik", 0, 16)); // NOI18N
        jLabel30.setText("Características");
        PainelRegistoProdutos1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        caracteristicaProduto1.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        caracteristicaProduto1.setToolTipText("Necessário");
        caracteristicaProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caracteristicaProduto1ActionPerformed(evt);
            }
        });
        PainelRegistoProdutos1.add(caracteristicaProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 240, 30));

        PainelRegistoProdutos.add(PainelRegistoProdutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 980, 470));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        setResizable(false);

        PainelRegistoUsuario.setBackground(new java.awt.Color(244, 255, 255));
        PainelRegistoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel31.setText("Nome ");
        PainelRegistoUsuario.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jL_nome.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jL_nome.setToolTipText("Necessário");
        jL_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_nomeActionPerformed(evt);
            }
        });
        PainelRegistoUsuario.add(jL_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 230, 30));

        jLabel32.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel32.setText("Modelo");
        PainelRegistoUsuario.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLpreco.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLpreco.setToolTipText("Necessário");
        jLpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLprecoActionPerformed(evt);
            }
        });
        PainelRegistoUsuario.add(jLpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 230, 30));

        jLabel35.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel35.setText("Quantidade");
        PainelRegistoUsuario.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel37.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel37.setText("Preço");
        PainelRegistoUsuario.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel38.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel38.setText("Estado");
        PainelRegistoUsuario.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jScrollPane1.setViewportView(jEditorPainelDescricao);

        PainelRegistoUsuario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 240, 90));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Registo de nova Peça");
        PainelRegistoUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 240, 30));

        jCestado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Novo", "Usado" }));
        jCestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCestadoActionPerformed(evt);
            }
        });
        PainelRegistoUsuario.add(jCestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 30));

        jLabel39.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel39.setText("Descrição");
        PainelRegistoUsuario.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLmodelo.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLmodelo.setToolTipText("Necessário");
        jLmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLmodeloActionPerformed(evt);
            }
        });
        PainelRegistoUsuario.add(jLmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 230, 30));

        jBtn_Save.setBackground(new java.awt.Color(244, 255, 255));
        jBtn_Save.setForeground(new java.awt.Color(244, 255, 255));
        jBtn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_done_all_black_24dp.png"))); // NOI18N
        jBtn_Save.setBorder(null);
        jBtn_Save.setBorderPainted(false);
        jBtn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SaveActionPerformed(evt);
            }
        });
        PainelRegistoUsuario.add(jBtn_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 40, 40));

        jLabel40.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel40.setText("Para carro");
        PainelRegistoUsuario.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jListModeloRef.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jListModeloRef.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Diversos", "Izusu", "Mazda", "Mitsubitsu", "Toyota" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListModeloRef);

        PainelRegistoUsuario.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 240, 60));

        jButton1.setBackground(new java.awt.Color(244, 255, 255));
        jButton1.setForeground(new java.awt.Color(244, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_arrow_back_black_36dp.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PainelRegistoUsuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 40, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 51, 0));
        PainelRegistoUsuario.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 412, 1000, 10));
        PainelRegistoUsuario.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 20));

        jSquant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PainelRegistoUsuario.add(jSquant, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelRegistoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelRegistoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCombCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombCategoriaItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jCombCategoriaItemStateChanged

    private void nomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoActionPerformed

    private void modeloProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloProdutoActionPerformed

    private void tipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoProdutoActionPerformed

    private void numeroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroProdutoActionPerformed

    private void estadoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoProdutoActionPerformed

    private void caracteristicaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caracteristicaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caracteristicaProdutoActionPerformed

    private void jCombCategoria1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombCategoria1ItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jCombCategoria1ItemStateChanged

    private void nomeProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProduto1ActionPerformed

    private void modeloProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloProduto1ActionPerformed

    private void tipoProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoProduto1ActionPerformed

    private void numeroProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroProduto1ActionPerformed

    private void estadoProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoProduto1ActionPerformed

    private void caracteristicaProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caracteristicaProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caracteristicaProduto1ActionPerformed

    private void jL_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_nomeActionPerformed

    private void jCestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCestadoActionPerformed

    private void jLmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLmodeloActionPerformed

    private void jBtn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SaveActionPerformed
        // TODO add your handling code here:
                
    if (jL_nome.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o Nome");
        jL_nome.requestFocus(); //Chama o cursor  
        
    }else if(!jL_nome.getText().matches("[a-zA-Z ,]+")){
            JOptionPane.showMessageDialog(null, "Nome inválido");
        }
    else if (jCestado.getSelectedItem().equals("Seleccione")){
        JOptionPane.showMessageDialog(null, "Seleccione o estado da peça");
        jCestado.requestFocus(); //Chama o cursor 
        
    }
    else if(jLpreco.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Informe o preço");
        jLpreco.requestFocus(); //Chama o cursor      
    }
   /* if(!jL_nome.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null, "Preço inválido");
        }*/
    else if (jSquant.getValue().equals(0)){
        JOptionPane.showMessageDialog(null, "Informe a quantidade");
        jSquant.requestFocus(); //Chama o cursor 
    
    }else{
        Produto pd = new Produto();
        pd.setNome(jL_nome.getText());
        pd.setQuantidade(Integer.parseInt( jSquant.getValue().toString()));
        if(Integer.parseInt( jSquant.getValue().toString())<30){
            pd.setAlerta(Alerta.ACABANDO);
        }else{
            pd.setAlerta(Alerta.EM_STOCK);
        }
        pd.setEstado((jCestado.getSelectedItem().toString()));
        pd.setModelo(jLmodelo.getText());
        pd.setPreco(Integer.parseInt(jLpreco.getText()));
        pd.setDescricao(jEditorPainelDescricao.getText());
        pd.setMarcaReferente(jListModeloRef.getSelectedValue());
        Registo rg = new Registo();
        rg.registarProduto(pd);
        }
    }//GEN-LAST:event_jBtn_SaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaMain tm = new TelaMain();
        setVisible(false);
        tm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLprecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelRegistoProdutos;
    private javax.swing.JPanel PainelRegistoProdutos1;
    private javax.swing.JPanel PainelRegistoUsuario;
    private javax.swing.JTextField caracteristicaProduto;
    private javax.swing.JTextField caracteristicaProduto1;
    private javax.swing.JEditorPane descricaoProduto;
    private javax.swing.JEditorPane descricaoProduto1;
    private javax.swing.JTextField estadoProduto;
    private javax.swing.JTextField estadoProduto1;
    private javax.swing.JButton jBtn_Save;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCestado;
    private javax.swing.JComboBox<String> jCombCategoria;
    private javax.swing.JComboBox<String> jCombCategoria1;
    private javax.swing.JEditorPane jEditorPainelDescricao;
    private javax.swing.JTextField jL_nome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JList<String> jListModeloRef;
    private javax.swing.JTextField jLmodelo;
    private javax.swing.JTextField jLpreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSquant;
    private javax.swing.JTextField modeloProduto;
    private javax.swing.JTextField modeloProduto1;
    private javax.swing.JTextField nomeProduto;
    private javax.swing.JTextField nomeProduto1;
    private javax.swing.JTextField numeroProduto;
    private javax.swing.JTextField numeroProduto1;
    private javax.swing.JTextField tipoProduto;
    private javax.swing.JTextField tipoProduto1;
    // End of variables declaration//GEN-END:variables

    
    //Utilites

}

