 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.mz.bennypecas.visao;

import co.mz.bennypecas.controladores.BuscaPecas;
import co.mz.bennypecas.modelos.Produto;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Euclidio G. Venâncio
 */
public class Venda extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    public Venda() {
        
        
        initComponents();
        //setSize(1000, 600);
          setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        preencherJTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLquantVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLnomeProdutoVenda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPainelDescricao = new javax.swing.JEditorPane();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLnomeProdutoVenda1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLnomeProdutoVenda2 = new javax.swing.JTextField();
        jtPesquisa = new javax.swing.JTextField();
        jbtnPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel1.setText("Vendas");

        jLabel31.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel31.setText("Descrição:");

        jLquantVenda.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLquantVenda.setToolTipText("Necessário");
        jLquantVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLquantVendaActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabela);

        jLabel32.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel32.setText("Preço por cada peça");

        jLnomeProdutoVenda.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLnomeProdutoVenda.setToolTipText("Necessário");
        jLnomeProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnomeProdutoVendaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jEditorPainelDescricao);

        jLabel33.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel33.setText("Quantidade:");

        jLabel34.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel34.setText("Produto:");

        jLnomeProdutoVenda1.setEditable(false);
        jLnomeProdutoVenda1.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLnomeProdutoVenda1.setToolTipText("Necessário");
        jLnomeProdutoVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnomeProdutoVenda1ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        jLabel35.setText("Preço Total a pagar:");

        jLnomeProdutoVenda2.setEditable(false);
        jLnomeProdutoVenda2.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jLnomeProdutoVenda2.setToolTipText("Necessário");
        jLnomeProdutoVenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnomeProdutoVenda2ActionPerformed(evt);
            }
        });

        jtPesquisa.setFont(new java.awt.Font("Rubik", 0, 15)); // NOI18N
        jtPesquisa.setToolTipText("Nome do produto a pesquisar");
        jtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisaActionPerformed(evt);
            }
        });

        jbtnPesquisa.setBackground(new java.awt.Color(244, 255, 255));
        jbtnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/worker.png"))); // NOI18N
        jbtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnPesquisa))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel33)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLquantVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel34)
                                            .addGap(44, 44, 44)
                                            .addComponent(jLnomeProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel31)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(jLnomeProdutoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel35)
                        .addGap(21, 21, 21)
                        .addComponent(jLnomeProdutoVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLquantVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31))
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLnomeProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLnomeProdutoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLnomeProdutoVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLquantVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLquantVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLquantVendaActionPerformed

    private void jLnomeProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnomeProdutoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLnomeProdutoVendaActionPerformed

    private void jLnomeProdutoVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnomeProdutoVenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLnomeProdutoVenda1ActionPerformed

    private void jLnomeProdutoVenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnomeProdutoVenda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLnomeProdutoVenda2ActionPerformed

    private void jtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesquisaActionPerformed

    private void jbtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesquisaActionPerformed
        // TODO add your handling code here:
        
       
        preencherJTablePesquisa(jtPesquisa.getText());
        
    }//GEN-LAST:event_jbtnPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JEditorPane jEditorPainelDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JTextField jLnomeProdutoVenda;
    private javax.swing.JTextField jLnomeProdutoVenda1;
    private javax.swing.JTextField jLnomeProdutoVenda2;
    private javax.swing.JTextField jLquantVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnPesquisa;
    private javax.swing.JTextField jtPesquisa;
    // End of variables declaration//GEN-END:variables


public void  preencherJTable(){


    ArrayList dados = new ArrayList();
    String [] colunas = new String [] {"Código","Nome","Estado","Modelo","Descrição","Preço","Quantidade","Situação"};
    
        BuscaPecas b = new BuscaPecas();
    
   
        for (Produto p: b.buscaTodos()){
            dados.add(new Object[]{p.getId(),p.getNome(),p.getEstado(),p.getModelo(),p.getDescricao(),p.getPreco(),p.getQuantidade(),p.getAlerta()});
        }
        
        BuscaPecas busca = new BuscaPecas(dados, colunas);
        
    Tabela.setModel(busca);
    Tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(0).setResizable(false);
    Tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(1).setResizable(false);
    Tabela.getColumnModel().getColumn(2).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(2).setResizable(false);
    Tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(3).setResizable(false);
    
    Tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(4).setResizable(false);
    
    Tabela.getColumnModel().getColumn(5).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(5).setResizable(false);
    Tabela.getColumnModel().getColumn(6).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(6).setResizable(false);
   Tabela.getColumnModel().getColumn(7).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(7).setResizable(false);
    //pega cabeçalho e cria a tabela
    Tabela.getTableHeader().setReorderingAllowed(false);
    Tabela.setAutoResizeMode(Tabela.AUTO_RESIZE_OFF);
    Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}


public void  preencherJTablePesquisa(String desc){


    ArrayList dados = new ArrayList();
    String [] colunas = new String [] {"Código","Nome","Estado","Modelo","Descrição","Preço","Quantidade","Situação"};
    
        BuscaPecas b = new BuscaPecas();
    
   
         for (Produto p: b.buscaTempoReal(desc)){
            dados.add(new Object[]{p.getId(),
                p.getNome(),p.getEstado(),
                p.getModelo(),
                p.getDescricao(),
                p.getPreco(),
                p.getQuantidade(),
                p.getAlerta()}
            );
        }
        
        BuscaPecas busca = new BuscaPecas(dados, colunas);
        
    Tabela.setModel(busca);
    Tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(0).setResizable(false);
    Tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(1).setResizable(false);
    Tabela.getColumnModel().getColumn(2).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(2).setResizable(false);
    Tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(3).setResizable(false);
    
    Tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(4).setResizable(false);
    
    Tabela.getColumnModel().getColumn(5).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(5).setResizable(false);
    Tabela.getColumnModel().getColumn(6).setPreferredWidth(100);
    Tabela.getColumnModel().getColumn(6).setResizable(false);
   Tabela.getColumnModel().getColumn(7).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(7).setResizable(false);
       Tabela.getColumnModel().getColumn(8).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(8).setResizable(false);
       Tabela.getColumnModel().getColumn(9).setPreferredWidth(150);
    Tabela.getColumnModel().getColumn(8).setResizable(false);
    //pega cabeçalho e cria a tabela
    Tabela.getTableHeader().setReorderingAllowed(false);
    Tabela.setAutoResizeMode(Tabela.AUTO_RESIZE_OFF);
    Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}


}
